name: databases
services:
  mongo:
    container_name: mongo_container
    image: mongo
    env_file:
      - ./hidden.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_vault:/data/db

  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_vault:/usr/local/etc/redis

  postgres:
    container_name: postgres_container
    env_file:
      - ./hidden.env
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_vault:/var/lib/postgresql/data

volumes:
  mongo_vault:
  redis_vault:
  postgres_vault:
