[versions]
junit = "5.10.0"
lombok = "1.18.36"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
