name: Brokers and Microservices
services:
  apache-kafka:
    image: apache/kafka
    container_name: kafka-broker
    networks: [ auth-same ]
    ports: [ "9092:9092" ]

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-gui
    ports: [ "8989:8080" ]
    depends_on: [ apache-kafka ]
    networks: [ auth-same ]
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  postgres-db:
    image: postgres
    container_name: postgres-queries-db
    networks: [ auth-same ]
    ports: [ "5431:5432" ]
    env_file: [ src/main/resources/hidden.env ]
    volumes: [ auth-postgres-db:/var/lib/postgresql/data ]

  root-application:
    container_name: root-application
    networks: [ auth-same ]
    ports: [ "8080:8080" ]
    depends_on: [ postgres-db, apache-kafka ]
    build:
      dockerfile: Dockerfile

volumes:
  auth-postgres-db:

networks:
  auth-same:
