name:
  intensive

services:
  db:
    env_file:
      - ./src/main/resources/hidden.env
    image: postgres
    networks:
      - same
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-app:
    env_file:
      - ./src/main/resources/hidden.env
    networks:
      - same
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8081:8080"

networks:
  same:

volumes:
  pg-data:
