services:
  db:
    env_file:
      - ./src/main/resources/hidden.env
    image: postgres
    networks:
      - same
    ports:
      - "5432:5432"

  spring-app:
    env_file:
      - ./src/main/resources/hidden.env
    networks:
      - same
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

networks:
    same:
