name: reviewdog
on: [pull_request]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.TEST_REPO_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: .github/workflows/checkstyle.xml
